import 'package:google_mlkit_pose_detection/google_mlkit_pose_detection.dart';

import 'authored_pose.dart';

// ─────────────────────────────────────────────────────────────────────────────
// EDR DECISION — Research Topic 07: Stage 7 — Serializer
// ─────────────────────────────────────────────────────────────────────────────
//
// Output: Dart source code (NOT a JSON file).
//
// Why Dart code instead of JSON?
//   JSON requires file I/O, a parser, and runtime deserialization.
//   Dart constants compile directly into the binary — O(1) load time.
//   For V1 (<20 poses), this is the fastest and safest approach.
//   When the library grows to 100+ poses, we can switch to JSON assets
//   without changing any engine code — only the target_poses.dart changes.
//
// Output format matches [TargetPoses.standingPose] exactly.
// The developer copies the output and pastes it into target_poses.dart.
// Zero runtime changes required.
// ─────────────────────────────────────────────────────────────────────────────
abstract final class PoseSerializer {
  /// Converts an [AuthoredPose] into a ready-to-paste Dart code snippet.
  ///
  /// Returns a multi-line string that the developer copies into
  /// [target_poses.dart] as a new static field.
  static String serialize(AuthoredPose pose) {
    final buffer = StringBuffer();
    final now = DateTime.now().toIso8601String().split('T').first;

    // ── Header comment ───────────────────────────────────────────────────────
    buffer.writeln('// Generated by Pose Authoring Pipeline — $now');
    buffer.writeln('// Source: ${pose.sourceImageName}');
    buffer.writeln(
        '// Quality: ${pose.qualityReport.passed ? "PASSED" : "FAILED"} '
        '| Coverage: ${pose.bodyCoverage.name} '
        '| Orientation: ${pose.orientation.name}');
    buffer.writeln(
        '// Camera Distance: ${pose.recommendedCameraDistance.name} '
        '| Symmetric: ${pose.isSymmetric} '
        '| Mirrored: ${pose.isMirrored}');
    buffer.writeln(
        '// Auto-Level: ${pose.correctedTiltDegrees.toStringAsFixed(1)}° corrected');
    buffer.writeln(
        '// Joint Angles — '
        'LElbow:${pose.jointAngles.leftElbow.toStringAsFixed(0)}° '
        'RElbow:${pose.jointAngles.rightElbow.toStringAsFixed(0)}° '
        'LKnee:${pose.jointAngles.leftKnee.toStringAsFixed(0)}° '
        'RKnee:${pose.jointAngles.rightKnee.toStringAsFixed(0)}°');
    buffer.writeln(
        '// Balance: CoM=(${pose.balance.comX.toStringAsFixed(2)}, '
        '${pose.balance.comY.toStringAsFixed(2)}) '
        'isBalanced=${pose.balance.isBalanced}');

    if (pose.qualityReport.warnings.isNotEmpty) {
      buffer.writeln('// Warnings:');
      for (final w in pose.qualityReport.warnings) {
        buffer.writeln('//   ⚠ $w');
      }
    }

    buffer.writeln();

    // Sanitize the pose ID to be a valid Dart variable name (camelCase).
    // e.g., "standing slightly bend" -> "standingSlightlyBend"
    String safeId = pose.id.trim().replaceAll(RegExp(r'[^a-zA-Z0-9\s]'), '');
    final words = safeId.split(RegExp(r'\s+'));
    if (words.length > 1) {
      safeId = words.first.toLowerCase() +
          words.skip(1).map((w) => w[0].toUpperCase() + w.substring(1)).join('');
    } else {
      safeId = safeId.toLowerCase();
    }
    if (safeId.isEmpty) safeId = 'myPose';

    // ── Dart static field declaration ─────────────────────────────────────
    buffer.writeln(
        'static final Map<PoseLandmarkType, FrozenLandmark> $safeId = {');

    // Sort landmarks by their PoseLandmarkType index for consistent output.
    final sortedEntries = pose.normalizedLandmarks.entries.toList()
      ..sort((a, b) => a.key.index.compareTo(b.key.index));

    for (final entry in sortedEntries) {
      final type = entry.key;
      final lm = entry.value;
      final x = lm.x.toStringAsFixed(4);
      final y = lm.y.toStringAsFixed(4);
      final likelihood = lm.likelihood.toStringAsFixed(2);
      buffer.writeln(
          '  PoseLandmarkType.${type.name}: '
          'FrozenLandmark(x: $x, y: $y, likelihood: $likelihood),');
    }

    buffer.writeln('};');
    buffer.writeln();

    // ── Joint importance weights ──────────────────────────────────────────
    // Stored as a comment for now — Engine 6 integration in a future update.
    buffer.writeln(
        '// Joint Importance Weights for ${pose.id} (for Engine 6):');
    buffer.writeln('// {');
    for (final entry in pose.jointImportanceWeights.entries) {
      // Convert the index back to a PoseLandmarkType name for readability.
      final typeName = _landmarkName(entry.key);
      buffer.writeln(
          '//   $typeName: ${entry.value.toStringAsFixed(2)},');
    }
    buffer.writeln('// }');

    return buffer.toString();
  }

  /// Returns the [PoseLandmarkType.name] for a given type index.
  static String _landmarkName(int index) {
    // Iterate through all known types to find a match.
    for (final type in PoseLandmarkType.values) {
      if (type.index == index) return type.name;
    }
    return 'unknown_$index';
  }
}
